name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: tempdbpassword
          MYSQL_DATABASE: pizza
        ports:
          - '3306:3306'
        options: >-
          --health-cmd "mysqladmin ping -ptempdbpassword" --health-interval 10s --health-start-period 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Write config file
        run: |
          echo "module.exports = {
            jwtSecret: '${{ secrets.JWT_SECRET }}',
            db: {
              connection: {
                host: '127.0.0.1',
                user: 'root',
                password: 'tempdbpassword',
                database: 'pizza',
                connectTimeout: 60000,
              },
              listPerPage: 10,
            },
            factory: {
              url: 'https://pizza-factory.cs329.click',
              apiKey: '${{ secrets.FACTORY_API_KEY }}',
            },
          };" > src/config.js

      - name: Tests
        run: npm test

      - name: set version
        id: set_version
        run: |
          version=$(date +'%Y%m%d.%H%M%S')
          echo "version=$version" >> "$GITHUB_OUTPUT"
          printf '{"version": "%s" }' "$version" > src/version.json
      - name: Debug secrets
        run: |
            echo "NET_ID length: ${#NET_ID}"
            echo "NET_ID starts with: ${NET_ID:0:3}"
            echo "API_KEY length: ${#FACTORY_API_KEY}"
            echo "API_KEY starts with: ${FACTORY_API_KEY:0:3}"
        env:
            NET_ID: ${{ secrets.NET_ID }}
            FACTORY_API_KEY: ${{ secrets.FACTORY_API_KEY }}
    
      - name: Update coverage
        env:
          NET_ID: ${{ secrets.NET_ID }}
          FACTORY_API_KEY: ${{ secrets.FACTORY_API_KEY }}
        run: |
            coverage=$(jq '.total.lines.pct' coverage/coverage-summary.json)
            color=$(echo "$coverage < 80" | bc | awk '{if ($1) print "red"; else print "green"}')
            echo "Coverage: $coverage"
            echo "Color: $color"
            response=$(curl -s -X POST "https://pizza-factory.cs329.click/api/badge/${NET_ID}/jwtpizzaservicecoverage?label=Coverage&value=$coverage%25&color=$color" -H "authorization: bearer ${FACTORY_API_KEY}")
            echo "Full badge service response: $response"